### ISSUE TITLE
Personas is giving weird error

### ISSUE THREAD

**Issue by galuszkak** [ggozad/behaving#26]
This is my traceback:

      Traceback (most recent call last):
        File "/Users/galuszkak/Projects/virtuals/evmgmt/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/Users/galuszkak/Projects/virtuals/evmgmt/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/Users/galuszkak/Projects/virtuals/evmgmt/lib/python2.7/site-packages/behaving/personas/persona.py", line 53, in replace
          value = context.persona.get_value(var)
      AttributeError: 'dict' object has no attribute 'get_value'

**Comment by ggozad** [comment]
Personas are again simple dicts.
